### ISSUE TITLE
Criar tela de Perfil de Empresa

### ISSUE THREAD

**Issue by jrsmarcilio** [jrsmarcilio/fourfood#40]
[Figma](https://www.figma.com/file/Wmd1c3eSeHIB61E4cSVENT/prog.mobile?node-id=150%3A316&t=Ri5Mw3ZDS8w5Moy6-0)

**Comment by philorocha** [comment]
Oi @maria-luiza-duda, implementamos essa tela em [DisplayLojaView.js](https://github.com/jrsmarcilio/fourfood/blob/5ad0bc09e48639f437dd27ac389156b73e408c2a/src/screens/DisplayLojaView.js).

**Comment by maria-luiza-duda** [comment]
Tela já implementada em [DisplayLojaView.js](https://github.com/jrsmarcilio/fourfood/blob/5ad0bc09e48639f437dd27ac389156b73e408c2a/src/screens/DisplayLojaView.js).
